### ISSUE TITLE
extended command history does not respect default directory when auto-saving

### ISSUE THREAD

**Issue by tollerm** [thierryvolpiatto/psession#13] opened 2020-05-07 07:11 UTC
Hi,
When auto-save-mode is on, I get these error messages:

error in process sentinel: async-handle-result: Opening output file: No such file or directory, /home/user/.emacs.d/elisp-objects/extended-command-history.el
error in process sentinel: Opening output file: No such file or directory, /home/user/.emacs.d/elisp-objects/extended-command-history.el

The value of psession-elisp-objects-default-directory is /home/user/.emacs.d/var/psession. Everything else works fine, the session parameters are saver when exiting Emacs session and restored after starting.

Thank you.

**Comment by thierryvolpiatto** [comment] 2020-05-07 08:46
tollerm <notifications@github.com> writes:

> Hi,
> When auto-save-mode is on, I get these error messages:
>
> error in process sentinel: async-handle-result: Opening output file: No such file or directory, /home/user/.emacs.d/elisp-objects/extended-command-history.el
> error in process sentinel: Opening output file: No such file or directory, /home/user/.emacs.d/elisp-objects/extended-command-history.el
>
> The value of psession-elisp-objects-default-directory is
> /home/user/.emacs.d/var/psession.

Hmm, seems the default value of
`psession-elisp-objects-default-directory` is used instead of yours.
Can you check once you have the error if the value of
`psession-elisp-objects-default-directory` is really
"/home/user/.emacs.d/var/psession/"? Use 
M-: psession-elisp-objects-default-directory RET

> Everything else works fine, the session parameters are saver when
> exiting Emacs session and restored after starting.
>
> Thank you.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.*


-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment] 2020-05-07 08:53
I tried right now and couldn't reproduce, here the config I used:

```elisp
(use-package psession
  :config
  (setq psession-elisp-objects-default-directory "/home/thierry/.emacs.d/var/psession/")
  (setq psession-auto-save-delay 20)
  (psession-savehist-mode 1)
  (psession-mode 1)
  (psession-autosave-mode 1)
```

**Comment by thierryvolpiatto** [comment] 2020-05-07 09:12
When changing my configuration, I had only one error when restarting emacs with the window configuration not found, this is now fixed.

**Comment by tollerm** [comment] 2020-05-07 17:00
I use almost the same configuration as yours. The only difference is that I do not set psession-elisp-objects-default-directory implicit. It is set by no-littering package.

**Comment by tollerm** [comment] 2020-05-07 18:06
Hi, 
I tried with your config and got exactly the same error that I had previously. It tries to save a variable in /home/user/.emacs.d/elisp-objects/ directory.

**Comment by thierryvolpiatto** [comment] 2020-05-08 05:57
tollerm <notifications@github.com> writes:

> I use almost the same configuration as yours. The only difference is
> that I do not set psession-elisp-objects-default-directory
> implicit. It is set by no-littering package.

So it is a problem with this package, which is perhaps working but I
guess it is not active at the time psession run, try with the exact path
of your directory.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tollerm** [comment] 2020-05-08 06:11
As I wrote previously, I tried with the exact pass set and I got the same error. What is strange, after some period the error message changed to

Psession: auto saving session...
error in process sentinel: async-handle-result: Invalid read syntax: "#"
error in process sentinel: Invalid read syntax: "#"

Something is wrong with async call of a function.

**Comment by thierryvolpiatto** [comment] 2020-05-08 07:19
tollerm <notifications@github.com> writes:

> As I wrote previously, I tried with the exact pass set and I got the
> same error.

Hmm the only possibility to have such error would be to have
"~/.emacs.d/elisp-objects/" hardcoded in psession.el and it is not the
case, so for now I don't know.

> What is strange, after some period the error message changed to
>
> Psession: auto saving session...
> error in process sentinel: async-handle-result: Invalid read syntax: "#"
> error in process sentinel: Invalid read syntax: "#"
>
> Something is wrong with async call of a function.

No, generally this is due to a variable containing strings with
properties (e.g. kill-ring), but normally psession handle this by
removing props before saving, I didn't have such errors since months
(years?).

> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.*


-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tollerm** [comment] 2020-05-08 08:45
Indeed, it is not hardcoded, however what C-h v gives me now:

psession-elisp-objects-default-directory is a variable defined in ‘psession.el’.
Its value is "/home/user/.emacs.d/var/psession/"
Original value was 
"~/.emacs.d/elisp-objects/"
  You can customize this variable.
Documentation:
The directory where lisp objects will be stored.

Only what I can suppose that the timer has been started with default directory and this directory name persists during the session. If I disable and then enable auto-save mode the error stil persists though.

However, I can live without auto-save functionality. Saving when killing Emacs session works flawless, that is enough for me. I will switch auto-save out.
Tnank you for your help.

**Comment by thierryvolpiatto** [comment] 2020-05-08 10:01
Oh, I found what's wrong, the child emacs is still using the default value `psession-elisp-objects-default-directory`, because I forget to inject the psession variables, this explain why psession is working as expected when quitting emacs and fail when auto saving. Will fix soon, let me know if it works once pushed.
Thanks.

**Comment by thierryvolpiatto** [comment] 2020-05-08 10:24
Ok, pushed, also I couldn't reproduce before the fix because I forgot to remove my old directory.

**Comment by tollerm** [comment] 2020-05-08 13:16
It works now! Thank you.

Something a little bit different. Can you make saving and restore winconf
and save-buffers optional? I don't need this because I want to start my Emacs session with a standard layout. While it is not difficult for me to remove these functions from emacs-startup hook, it will be more user friendly to have the options something like that (setq save-winconf t save-buffers t).
Thank you once more again,
Toller

**Comment by thierryvolpiatto** [comment] 2020-05-08 16:32
tollerm <notifications@github.com> writes:

> It works now! Thank you.

Great!

> Something a little bit different. Can you make saving and restore winconf
> and save-buffers optional?

Did you try to remove `psession--winconf-alist` assoc from
`psession-object-to-save-alist` and set
`psession-save-buffers-unwanted-buffers-regexp` to ".*"?

Fully not tested, so no guarantee it works, I will look more carefully
tomorrow.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tollerm** [comment] 2020-05-08 17:10
I did not know about regexp option. It is certainly worth to mention about it in Readme.

**Comment by tollerm** [comment] 2020-05-08 17:15
And one more request. Can you make adding a variable to be persistent more easier. Something like that (not tested):
(defun make-var-persistent (var)
  "Make VAR persistent."
  (when (boundp var)
    (add-to-list 'psession-object-to-save-alist
                 (cons var  (format "%s.el" (symbol-name var))))))

**Comment by thierryvolpiatto** [comment] 2020-05-09 08:04
tollerm <notifications@github.com> writes:

> And one more request. Can you make adding a variable to be persistent
> more easier.

Done, this is `psession-make-persistent-variable` read its docstring.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tollerm** [comment] 2020-05-09 11:24
Thank you! It works really nice, especially integration with Helm in interactive mode is nifty. 
Keep good work,
Toller

**Closed** 2020-09-20 07:32 UTC
